"""
Django settings for gestor_mascotas project.

Generated by 'django-admin startproject' using Django 6.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# En local usa la key de siempre; en Render se define SECRET_KEY como
# variable de entorno con un valor real y secreto.
SECRET_KEY = os.environ.get(
    'SECRET_KEY',
    'django-insecure-c%&*#%99$g=e)+8b+s4b^bo1#aa#p2!52zfz_7kx_4@$9wi=rg',
)

# SECURITY WARNING: don't run with debug turned on in production!
# En Render se define DJANGO_DEBUG=False como variable de entorno.
DEBUG = os.environ.get('DJANGO_DEBUG', 'True') == 'True'

# admite cualquier subdominio *.onrender.com automaticamente (no hay que
# escribir la URL exacta a mano), mas lo que se agregue por variable de entorno
ALLOWED_HOSTS = ['.onrender.com', 'localhost', '127.0.0.1']
extra_hosts = os.environ.get('ALLOWED_HOSTS', '')
if extra_hosts:
    ALLOWED_HOSTS += [h.strip() for h in extra_hosts.split(',') if h.strip()]

# necesario porque Render sirve la app detras de un proxy https
CSRF_TRUSTED_ORIGINS = ['https://*.onrender.com']

# seguridad basica cuando corre en produccion (Render siempre sirve por https)
if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'mascotas',
    'tienda',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # sirve los archivos estaticos en produccion (admin, etc)
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'gestor_mascotas.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'gestor_mascotas.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases
#
# En local (sin DATABASE_URL definida) usa SQLite, igual que antes.
# En Render se define DATABASE_URL con el connection string de un proyecto
# de Neon (PostgreSQL) para que los datos NO se borren cada vez que Render
# reinicia el servicio (el disco de Render es temporal, un archivo sqlite3
# ahi se perderia).

import dj_database_url

DATABASES = {
    'default': dj_database_url.config(
        default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}",
        conn_max_age=600,
    )
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'  # aqui junta collectstatic los archivos para produccion
STORAGES = {
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
    },
}

# URL del microservicio de curiosidades (Node.js + Neon), desplegado en Render.
# En local usa localhost:3000; en produccion se define con la variable de entorno.
MICROSERVICIO_URL = os.environ.get('MICROSERVICIO_URL', 'http://localhost:3000')
# CRUD y consulta resiliente: en Render se configuran las URLs de servicios independientes.
CRUD_INSERTAR_URL = os.environ.get('CRUD_INSERTAR_URL', '')
CRUD_ACTUALIZAR_URL = os.environ.get('CRUD_ACTUALIZAR_URL', '')
CRUD_ELIMINAR_URL = os.environ.get('CRUD_ELIMINAR_URL', '')
CONSULTA_PYTHON_URL = os.environ.get('CONSULTA_PYTHON_URL', '')
CONSULTA_NODE_URL = os.environ.get('CONSULTA_NODE_URL', '')


# IA externa gratuita (Groq: https://console.groq.com, tiene capa gratuita).
# Api compatible con el formato de chat completions de OpenAI.
GROQ_API_KEY = os.environ.get('GROQ_API_KEY', '')
GROQ_API_URL = 'https://api.groq.com/openai/v1/chat/completions'
GROQ_MODEL = 'openai/gpt-oss-20b'


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}
