# Generated by Django 6.1.1 on 2026-09-22 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('precio_felicidad', models.IntegerField(help_text='Cuanta felicidad da')),
                ('reduce_hambre', models.IntegerField(help_text='Cuanto hambre quita')),
                ('emoji', models.CharField(default='🎁', max_length=5)),
            ],
        ),
    ]
