# Generated by Django 6.1.1 on 2026-09-26 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0002_mascota_ultima_interaccion'),
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='costo',
            field=models.IntegerField(default=10, help_text='Costo en monedas del minijuego'),
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=0)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.item')),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventario', to='mascotas.mascota')),
            ],
            options={
                'unique_together': {('mascota', 'item')},
            },
        ),
    ]
