# Generated by Django 6.1.1 on 2026-09-22 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('especie', models.CharField(choices=[('perro', 'Perro'), ('gato', 'Gato'), ('dragon', 'Dragón'), ('robot', 'Robot')], default='perro', max_length=20)),
                ('hambre', models.IntegerField(default=50)),
                ('felicidad', models.IntegerField(default=50)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
