# Generated by Django 6.1.1 on 2026-09-26 02:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='ultima_interaccion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
